baseURL = "https://www.example.com/"
title = "WeUI"
theme ="weui"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true
paginate=3
# copyright="xxx"
pygmentsCodefences=false  # to use highlight js

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Basic personal site theme styled with weiui, syntax highlighting."

[[menu.main]]
  name = "blog"
  url = "posts/"
  weight = 1

[[menu.main]]
  name = "tags"
  url = "tags/"
  weight = 1
  

[[menu.main]]
  name = "about"
  url = "about/"
  weight = 2
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true